url: "https://travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com/v1/prices/cheap"


x-rapidapi-host: "travelpayouts-travelpayouts-flight-data-v1.p.rapidapi.com"

x-rapidapi-key: "af57958cf8msh7a41980e6313f7dp11972ajsn2f30f1957320"
X-Access-Token: "25ced8893baf9bcb20657fa1c3703700"

destination:
origin:
return_date:
depart_date:
currency:


#querystring: {
              #"destination":"Barcelona",
              #"origin":"Madrid",
              #"return_date":"2022-04",
              #"depart_date":"2022-04",
              #"currency":"EUR"
              #}
